### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got NoneType

### ISSUE THREAD

**Issue by phyukhaing7** [mikkkeldp/hard-attention-image-captioning#2]
In the evaluation process, I faced with the following error:

```
Evaluating on test set...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 102, in <module>
    main(args)
  File "eval.py", line 76, in main
    for _, (images, captions, ids) in tqdm(enumerate(data_loader)):
  File "/home/user/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/user/New Volume/CODE/internet/22.7.2021/hard-attention-image-captioning-main/data_loader.py", line 157, in collate_fn2
    images = torch.stack(images, 0)
TypeError: expected Tensor as element 0 in argument 0, but got NoneType

```

**Comment by mikkkeldp** [comment]
Oh no. I'll try fix later today as i'm not currently at my pc

**Comment by phyukhaing7** [comment]
May I know that you used the version of packages for the pytorch.

**Comment by mikkkeldp** [comment]
Sorry for taking so long. This repo was used for experimentation on top of the Hard attention model that eventually split into a new repo and caused all these bugs. I fixed the issues you brought up and everything should be working now.
